### ISSUE TITLE
Version without System.Collections.Specialized

### ISSUE THREAD

**Issue by patook** [drasticactions/GiphyDotNet#1]
Thanks for building this. FYI that it doesn't compile on Xamarin since the NameValueCollection is not supported in that version of Mono.

A simple fix for me was to get the source code and implement my own mini-NameValueCollection. I don't have the latest code in front of me but it was something like:

public class NameValueCollection : Dictionary<string, List<string>>
    {
        public void Add(string s, string o)
        {
            if (this.ContainsKey (s))
                this [s].Add (o);
            else
                this [s] = new List<string> () {o};
        }

```
    public KeyCollection AllKeys()
    {
        return Keys;
    }

    public List<string> GetValues(string s)
    {
        return this [s];
    }

}
```

**Comment by drasticactions** [comment]
Already removed.
