### ISSUE TITLE
Could not load file or assembly 'System.Collections.Specialized

### ISSUE THREAD

**Issue by Geaven** [drasticactions/GiphyDotNet#3]
I'm trying to build a discord bot that will search for the command and show the corresponding gif but i keep getting the error System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Collections.Specialized, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=GiphyDotNet

**Comment by Geaven** [comment]
I've fixed the issue above, but how do I use the gifResult though, is it possible to just get the URL?

**Comment by drasticactions** [comment]
Doesn't use Specialized collections anymore, removed.
