### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by OniSensei** [drasticactions/GiphyDotNet#5]
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=##########' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Not compatible with newtonsoft.json.dll v 12.0.0.0?

**Comment by drasticactions** [comment]
Doesn't use JSON.NET anymore, closed.
