### ISSUE TITLE
Adding 'lang' search parameter

### ISSUE THREAD

**Issue by Arnaud-F** [drasticactions/GiphyDotNet#6]
Hello,

Regarding the #search api endpoint, it is possible to add a language prop that is currently not available in this api.
Link: https://developers.giphy.com/docs/api/endpoint#search

Would it be possible to add it? CultureInfo is your friend.

Best regards,

**Comment by drasticactions** [comment]
Should be fixed with https://github.com/drasticactions/GiphyDotNet/commit/6a5149e548b1a579a03fc34517278af0c66d401d
