### ISSUE TITLE
No ImagUrl passed anymore

### ISSUE THREAD

**Issue by pvrobays** [drasticactions/GiphyDotNet#8]
I think because of changes in the returned JSON result for random gifs, there's no more ImageUrl passed.
The JSON parser tries to look for "image_url", but the gif url image seems to reside under "images" -> "original" -> "url".

In fact, the only available result seems to be the gif ID, Type and Url.

This issue renders this SDK as nearly useless 😢

**Comment by drasticactions** [comment]
Fixed with https://github.com/drasticactions/GiphyDotNet/commit/07974bcaf59e722a42c5f4c3c32744fe987c641e
